module.exports = {
  apps: [
    {
      name: "bedagang-hq",
      cwd: "/home/ubuntu/bedagang-pos",
      script: "node_modules/next/dist/bin/next",
      args: "dev --port 3001",
      env: {
        NODE_ENV: "development",
        PORT: "3001",
        NEXTAUTH_URL: "http://43.129.56.221:3001",
        NEXTAUTH_SECRET: "bedagang-erp-super-secret-key-vps-2026-nainerp",
        DATABASE_URL: "postgresql://bedagang:***@localhost:5433/bedagang_dev?sslmode=disable",
        DB_HOST: "localhost",
        DB_PORT: "5433",
        REDIS_URL: "redis://localhost:6379",
        JWT_SECRET: "bedagang-jwt-secret-vps-2026-nainerp-key",
        ENABLE_LOYALTY_PROGRAM: "true",
        ENABLE_MULTI_BRANCH: "true",
        DEFAULT_CURRENCY: "IDR",
        DEFAULT_TIMEZONE: "Asia/Jakarta",
        DEFAULT_LANGUAGE: "id",
      },
      instances: 1,
      exec_mode: "fork",
      watch: false,
      max_memory_restart: "1G",
      error_file: "/home/ubuntu/logs/bedagang-hq-error.log",
      out_file: "/home/ubuntu/logs/bedagang-hq-out.log",
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
    },
    {
      name: "bedagang-store",
      cwd: "/home/ubuntu/bedagang-pos",
      script: "node_modules/next/dist/bin/next",
      args: "dev --port 3002",
      env: {
        NODE_ENV: "development",
        PORT: "3002",
        NEXTAUTH_URL: "http://43.129.56.221:3002",
        NEXTAUTH_SECRET: "bedagang-erp-super-secret-key-vps-2026-nainerp",
        DATABASE_URL: "postgresql://bedagang:***@localhost:5433/bedagang_dev?sslmode=disable",
        DB_HOST: "localhost",
        DB_PORT: "5433",
        REDIS_URL: "redis://localhost:6379",
        JWT_SECRET: "bedagang-jwt-secret-vps-2026-nainerp-key",
        ENABLE_LOYALTY_PROGRAM: "true",
        ENABLE_MULTI_BRANCH: "true",
        DEFAULT_CURRENCY: "IDR",
        DEFAULT_TIMEZONE: "Asia/Jakarta",
        DEFAULT_LANGUAGE: "id",
      },
      instances: 1,
      exec_mode: "fork",
      watch: false,
      max_memory_restart: "1G",
      error_file: "/home/ubuntu/logs/bedagang-store-error.log",
      out_file: "/home/ubuntu/logs/bedagang-store-out.log",
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
    },
    {
      name: "bedagang-backend",
      cwd: "/home/ubuntu/bedagang-pos/backend",
      script: "/home/ubuntu/bedagang-pos/backend/dist/server.js",
      env: {
        NODE_ENV: "production",
        PORT: "4000",
        DB_HOST: "localhost",
        DB_PORT: "5433",
        DB_NAME: "bedagang_dev",
        DB_USER: "bedagang",
        DB_PASSWORD: "bedagang123",
        REDIS_HOST: "localhost",
        REDIS_PORT: "6379",
        JWT_SECRET: "bedagang-jwt-secret-vps-2026-nainerp-key",
      },
      instances: 1,
      exec_mode: "fork",
      watch: false,
      max_memory_restart: "512M",
      error_file: "/home/ubuntu/logs/bedagang-backend-error.log",
      out_file: "/home/ubuntu/logs/bedagang-backend-out.log",
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
    },
  ],
};
