#!/usr/bin/env bash
# ==========================================
# Bedagang ERP — Deploy Script
# ==========================================
# Usage: bash deploy/deploy.sh
# Run from /home/ubuntu/bedagang-pos/
# ==========================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

echo "======================================"
echo "  Bedagang ERP — Production Deploy"
echo "======================================"

# ─── 1. Check prerequisites ──────────────
echo "[1/5] Checking prerequisites..."

command -v docker >/dev/null 2>&1 || { echo "ERROR: docker not found"; exit 1; }
docker compose version >/dev/null 2>&1 || { echo "ERROR: docker compose not found"; exit 1; }
command -v nginx >/dev/null 2>&1 || echo "WARN: nginx not installed locally"

echo "  ✓ docker: $(docker --version)"
echo "  ✓ compose: $(docker compose version --short)"

# ─── 2. Environment file ─────────────────
echo "[2/5] Setting up .env..."

if [ ! -f .env ]; then
    if [ -f .env.example ]; then
        cp .env.example .env
        echo "  ✓ Created .env from .env.example"
        echo "  ⚠ IMPORTANT: Edit .env with production secrets!"
    else
        echo "  ✗ No .env.example found — creating minimal .env"
        cat > .env << 'ENVEOF'
# Generated by deploy script — EDIT SECRETS
DB_USER=bedagang
DB_PASSWORD=changeme_production_password
NEXTAUTH_SECRET=changeme_nextauth_secret
SESSION_SECRET=changeme_session_secret
JWT_SECRET=changeme_jwt_secret
JWT_REFRESH_SECRET=changeme_jwt_refresh_secret
NODE_ENV=production
DOMAIN=43.129.56.221
ENVEOF
    fi
else
    echo "  ✓ .env already exists"
fi

# ─── 3. Nginx configuration ──────────────
echo "[3/5] Setting up Nginx..."

NGINX_SSL_DIR="/etc/nginx/ssl/bedagang"
NGINX_SITES="/etc/nginx/sites-available"
NGINX_ENABLED="/etc/nginx/sites-enabled"

# Ensure SSL cert exists
if [ ! -f "$NGINX_SSL_DIR/bedagang.crt" ]; then
    echo "  Creating self-signed SSL certificate..."
    sudo mkdir -p "$NGINX_SSL_DIR"
    sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout "$NGINX_SSL_DIR/bedagang.key" \
        -out "$NGINX_SSL_DIR/bedagang.crt" \
        -subj '/C=ID/ST=Jakarta/L=Jakarta/O=Bedagang/CN=43.129.56.221'
    sudo chmod 600 "$NGINX_SSL_DIR/bedagang.key"
    sudo chmod 644 "$NGINX_SSL_DIR/bedagang.crt"
    echo "  ✓ Self-signed cert created"
else
    echo "  ✓ SSL cert already exists"
fi

# Install nginx config
if [ -f "deploy/nginx/bedagang-selfsigned.conf" ]; then
    sudo cp "deploy/nginx/bedagang-selfsigned.conf" "$NGINX_AVAILABLE/bedagang"
    if [ ! -f "$NGINX_ENABLED/bedagang" ]; then
        sudo ln -sf "$NGINX_AVAILABLE/bedagang" "$NGINX_ENABLED/bedagang"
    fi
    echo "  ✓ Nginx config installed"
elif [ -f "deploy/nginx/bedagang.conf" ]; then
    sudo cp "deploy/nginx/bedagang.conf" "$NGINX_AVAILABLE/bedagang"
    if [ ! -f "$NGINX_ENABLED/bedagang" ]; then
        sudo ln -sf "$NGINX_AVAILABLE/bedagang" "$NGINX_ENABLED/bedagang"
    fi
    echo "  ✓ Nginx config installed"
fi

# Test and reload nginx
sudo nginx -t && sudo systemctl reload nginx || sudo systemctl restart nginx
echo "  ✓ Nginx reloaded"

# ─── 4. Docker Compose ──────────────────
echo "[4/5] Building and starting Docker services..."

# Build images (this takes a while the first time)
docker compose -f bedagang-docker-compose.yml build --parallel

# Start services
docker compose -f bedagang-docker-compose.yml up -d

echo "  ✓ Services started"

# ─── 5. Health check ────────────────────
echo "[5/5] Running health checks..."
sleep 5

check_service() {
    local name=$1
    local container=$2
    if docker ps --format '{{.Names}}' | grep -q "^$container$"; then
        local status=$(docker inspect "$container" --format '{{.State.Health.Status}}' 2>/dev/null || echo "no healthcheck")
        echo "  ✓ $name ($container): $status"
    else
        echo "  ✗ $name ($container): NOT RUNNING"
    fi
}

check_service "Admin" "bedagang-admin"
check_service "Store" "bedagang-store"
check_service "API" "bedagang-api"
check_service "PostgreSQL" "bedagang-db"
check_service "Redis" "bedagang-redis"

echo ""
echo "======================================"
echo "  Bedagang ERP Deploy Complete!"
echo "======================================"
echo "  Admin:  https://43.129.56.221/admin"
echo "  Store:  https://43.129.56.221/"
echo "  API:    https://43.129.56.221/api/"
echo "======================================"
